Rename pitch to speed, added example, and tweaked existing sound example
pythonarcade/arcade pull request #1216
Opened 2022-05-07 19:05 UTC by iansedano

Mainly renaming the `pitch` parameter to `speed` as per #1198. I also reverted the change to the `asteroid_smasher.py` example and created a standalone `sound_speed_demo.py` example.

I also tweaked the original `sound_demo.py` to make it a bit more concise before I created the speed demo from that template. I thought about renaming `sound_demo.py`, since it is mainly demonstrating panning. Further, I'd probably move the streaming button (in `sound_demo.py`) into it's own example, because it seems to be demonstrating something different, and it also crashes if you press it twice in quick succession.

I didn't yet, though, because that would probably mess with the diff, and that could be done in another PR.

2022-05-07 19:09 UTC, iansedano commented
I'm seeing that the tests are failing due to my "table", any ideas? If not, I'll find another way, later.

2022-05-07 19:20 UTC, Ibrahim2750mi commented
> I'm seeing that the tests are failing due to my "table", any ideas? If not, I'll find another way, later.

Does doing "flake8 file_name.py" return nothing? Also theres a discussion(on discord) going on whether to change the naming of  `pitch` or not

2022-05-10 02:09 UTC, pushfoo commented
@iansedano you can click `details` on the right-hand side of any CI check to see more information:
![image](https://user-images.githubusercontent.com/36696816/167527888-dacb1d98-bcb4-4c14-8ef3-60f51f57d8da.png)
For either of the runs above, doing should automatically scroll you to the code-inspection section, which will list issues:
![image](https://user-images.githubusercontent.com/36696816/167528067-cb8f9578-37fd-4d10-9195-7bcc42e3b31e.png)
The way you have your arguments formatted isn't something that python likes. I'll try to make some suggestions on a more pythonic way to format your code in the next 24 hours.

2022-05-11 04:20 UTC, pushfoo requested changes
I think there's room for changes beyond ones to make the linters happy.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_demo.py
> +        button_params = [
Even if we think it looks nice, python style guides strongly disagree with this sort of formatting.

One way to deal with it is to span this across two for loops: the outer one handles setting the row y position, and the inner one passes the `pan` and `vol` columns in.

If you want to be explicit about the panning volumes, maybe you can put those in a tuple constant stored at the top?

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    NOTE: Go ahead and delete the methods you don't need.
I would delete this comment, as well as the methods that are stubbed out with `pass`.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    NOTE: Go ahead and delete the methods you don't need.
I would delete this comment, as well as the methods that are stubbed out with `pass`.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +        #    sound        , speed, vol   , x                          , y
You could probably use the same nested for loop for loop approach suggested above here.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +        #    sound        , speed, vol   , x                          , y
You could probably use the same nested for loop for loop approach suggested above here.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_mouse_release(self, x, y, button, key_modifiers):
probably best to delete this if we're not using it.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_mouse_release(self, x, y, button, key_modifiers):
probably best to delete this if we're not using it.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_key_press(self, key, key_modifiers):
delete this method if it's just a stub

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_key_press(self, key, key_modifiers):
delete this method if it's just a stub

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_key_release(self, key, key_modifiers):
delete this method if it's just a stub

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_key_release(self, key, key_modifiers):
delete this method if it's just a stub

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_mouse_motion(self, x, y, delta_x, delta_y):
delete this method if it's just a stub

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    def on_mouse_motion(self, x, y, delta_x, delta_y):
delete this method if it's just a stub

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/text_loc_example_done.py
> +            _("Simple line of text in 12 point"),
Although this change makes sense, why is it in this PR? I thought this was supposed to be sounds-specific.

2022-05-11 04:20 UTC, pushfoo commented on arcade/examples/text_loc_example_done.py
> +            _("Simple line of text in 12 point"),
Although this change makes sense, why is it in this PR? I thought this was supposed to be sounds-specific.

2022-05-11 04:20 UTC, pushfoo commented on arcade/sound.py
> +        player.pitch = speed # note that the underlying attribute is pitch but "speed" is used because it better describes the behavior see #1198
It's probably best to break this up as a multiple comment lines above setting the pitch on the player. The linters won't like this as-is.

2022-05-11 04:20 UTC, pushfoo commented on arcade/sound.py
> +        player.pitch = speed # note that the underlying attribute is pitch but "speed" is used because it better describes the behavior see #1198
It's probably best to break this up as a multiple comment lines above setting the pitch on the player. The linters won't like this as-is.

2022-05-15 18:05 UTC, iansedano commented
Thanks for the review @pushfoo!

I've made the changes you mentioned, mainly changing the way the buttons were created and general cleaning up.

2022-05-16 20:27 UTC, pushfoo approved these changes
@iansedano There are some minor stylistic issues where things look a little JS and less python, but this is otherwise good!
My understanding is that we might merge it with some style fixes down the line since there may be a minor release getting made soon.

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_demo.py
> +        button_params = [
Even if we think it looks nice, python style guides strongly disagree with this sort of formatting. :frowning: 

One way to deal with it is to span this across two for loops: the outer one handles setting the row y position, and the inner one passes updated x position, `pan`, and `vol` values.

If you want to be explicit about the panning volumes, maybe you can put those in a tuple constant stored at the top?

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +    assert speed > 0
If you're trying to ensure the length of the array is the same for the x positions and the speeds, it might make more sense to generate the values dynamically in one place.

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +        button_x_spread = [
This could be either a constant at the top of the file or dynamically generated.

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_demo.py
> +            for pan_setting, x_pos in zip(SOUND_PANNING, button_x_spread):
Although this `zip`-based approach might confuse some beginners, it's very concise and I think I like the idea. :+1:

It'd be helpful for beginners if you add some comments with the following:
1. A few words explaining what `zip` does
2. A link to the python doc for `zip`: https://docs.python.org/3/library/functions.html#zip

Maybe something like this?
```py
# Arrange the buttons in a grid
# The zip function puts pieces of two iterables together
# For more information, see the python doc:
# https://docs.python.org/3/library/functions.html#zip
```

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_speed_demo.py
> +            for speed_setting, x_pos in zip(SPEED_VARIATION, button_x_spread):
Same comment as for the other example: it's unexpected but it's concise :+1:. Add a brief comment to explain what `zip` does, possibly with a link to the python doc. https://docs.python.org/3/library/functions.html#zip

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_demo.py
> +        button_x_spread = [
In its current form, this would be better put in a constant at the top of the file.

2022-05-16 20:27 UTC, pushfoo commented on arcade/examples/sound_demo.py
> +assert len(SOUND_PANNING) == 5
This might not make sense to keep. It would be better to move related constants here with a comment, or dynamically generate this.

2022-05-16 20:47 UTC, einarf commented
Let's just merge this in and do some final tweaks.

2022-05-16 20:49 UTC, merged