Adds additional shader examples to docs
pythonarcade/arcade pull request #1455
Opened 2023-01-11 13:28 UTC by user2332533

These examples cover adding inputs (uniforms and buffers) to a shader. 

This follows on from the help provided in issue #1453 

These examples cover:
- A very basic vertex/frament shader
- Passing a number as a uniform
- Accessing multiple textures from a shader
- rendering to a new frambuffer texture

Only one additional housekeeping change was made:
- Moves gpu_particle_burst into the shaders submenu 

Tested locally, build succeeded and docs look fine.

2023-01-11 21:47 UTC, pushfoo commented
Small nitpick: I'd rephrase the PR title as "Add additional shader tutorials" since the examples and tutorials folders are separate, and this PR adds content to the tutorials.

2023-01-11 21:54 UTC, pvcraven commented on doc/tutorials/shader_inputs/index.rst
> +Basic Pygame Program
Arcade, not Pygame

2023-01-11 22:06 UTC, user2332533 commented on doc/tutorials/shader_inputs/index.rst
> +Basic Pygame Program
Ooops, corrected in 9b8614

2023-01-24 20:03 UTC, csd4ni3l commented
hmmmmm "Basic Pygame Program" in the "add shader examples to docs" commit in the index.rst file :laughing:

2023-01-24 20:39 UTC, user2332533 commented
Hopefully now with 100% fewer mistaken names. 

🤦‍♂️

2023-01-27 19:06 UTC, pvcraven commented
I left a couple comments which were just simple formatting type things. Are you able to correct? 

This seems like a worth-while addition to docs.

2023-01-30 14:34 UTC, user2332533 commented
Hi Paul,

Sorry if I'm being dense, but I cannot find your comments for formatting etc. I'm happy to fix any issues but don't know where I should be looking for the comments.

2023-01-30 14:35 UTC, csd4ni3l commented
just look at the changes of your commits(click on the commit) and it will appear there

2023-01-30 19:54 UTC, user2332533 commented
I've gone through all of the commits on this PR and the only comment I can see was Paul's Observation about the wrong library name, I corrected this in the second commit [9b86b14](https://github.com/pythonarcade/arcade/pull/1455/commits/9b86b14bb808a464b0a190357b2a2cc4e4d13eb8) and marked as resolved.

2023-01-30 19:58 UTC, pvcraven requested changes

2023-01-30 19:58 UTC, pvcraven commented on doc/tutorials/shader_inputs/index.rst
> +================================
Line too long, Sphinx will complain if it doesn't match the header.

2023-01-30 19:58 UTC, pvcraven commented on doc/tutorials/shader_inputs/index.rst
> +To pass data to the shader program we can define `uniforms <https://www.khronos.org/opengl/wiki/Uniform_(GLSL)>`_. Uniforms are global shader variables that act as parameters passed from outside the
I know not everyone follows this, but I like keeping about an 80 char max on line-length for text.

2023-01-30 19:59 UTC, pvcraven commented
> I've gone through all of the commits on this PR and the only comment I can see was Paul's Observation about the wrong library name, I corrected this in the second commit [9b86b14](https://github.com/pythonarcade/arcade/pull/1455/commits/9b86b14bb808a464b0a190357b2a2cc4e4d13eb8) and marked as resolved.

I didn't hit the 'finish review' button.

2023-02-01 15:14 UTC, pvcraven approved these changes

2023-02-01 15:20 UTC, pvcraven commented
Will need to look at why this test is failing, don't think it has anything to do with the PR.

2023-02-01 16:03 UTC, pvcraven commented
> Will need to look at why this test is failing, don't think it has anything to do with the PR

Currently failing because of an unrelated issue around a test and pyglet's 2.0.4 release. That'll need to get cleaned up separate from this.

2023-02-01 16:21 UTC, merged