add constants for F17-F24
pythonarcade/arcade pull request #1516
Opened 2023-02-13 21:46 UTC by DigiDuncan

Tested by binding a key in Razer Synpase to F17-F24, printing the value returned from `on_key_press()`, and setting the constant value to what was returned.

2023-02-14 03:36 UTC, pushfoo requested changes
This isn't a spurious failure from connectivity issues. There's a CI check that needs to be updated.

2023-02-14 03:36 UTC, pushfoo commented on arcade/key/__init__.py
> +F24 = 579820584960
Change the 206 in this file to 214 and the build should pass:
https://github.com/pythonarcade/arcade/blob/2c4fd952223fe86dc8fbba958e90f3103cbd9c99/tests/unit/test_key.py#L2-L5

2023-02-14 16:36 UTC, einarf commented
These are window only then? It would pobably be better doing this change in pyglet? I'm not entirely sure.

2023-02-15 22:58 UTC, DigiDuncan commented
Updated the constants to match pyglet's implementation. These do not currently work, because pyglet's backend does not support F17-F24 yet, but will in a future update (https://github.com/pyglet/pyglet/pull/773).

2023-02-19 16:31 UTC, pvcraven commented
Are you going to update the unit test so this passes? Far as I can tell, that's the only thing keeping it from being merged.

2023-02-19 22:44 UTC, DigiDuncan commented
> Are you going to update the unit test so this passes? Far as I can tell, that's the only thing keeping it from being merged.

Done and done, apologies for the wait time.

2023-02-19 23:01 UTC, pushfoo approved these changes
It looks ready to merge now.

2023-02-21 14:25 UTC, merged