Minor improvements to GUI system
pythonarcade/arcade pull request #1690
Opened 2023-04-07 15:22 UTC by eschan145

The parameter docs look very ugly and compacted with the native RST formatting. Switching to Google-style would also leave me with more space to fit more characters per line.

2023-04-07 23:58 UTC, gran4 commented on arcade/gui/widgets/text.py
> +
I think you should delete this space.

2023-04-07 23:58 UTC, gran4 commented on arcade/gui/widgets/text.py
> +        """Text of the widget. Modifying this repeatedly will cause significant
Move Text(the entire line) after """

2023-04-07 23:58 UTC, gran4 commented on arcade/gui/widgets/text.py
> +        """Multiline state of the widget. Newlines indicated with ``\n`` will
Move Multiline(the entire line) after """

2023-04-07 23:58 UTC, gran4 commented on arcade/gui/widgets/text.py
> +        """Internal :py:class:`~arcade.gui.UILabel` used for rendering the
Move Internal(the entire line) after """

2023-04-08 10:45 UTC, pushfoo reviewed
Good catch on `Caret` being RGB-only in pyglet's source. That's something which needs to be addressed upstream. I'll give this PR a more thorough look later.

EDIT: I filed a ticket with pyglet checking for any blockers for making `Caret` take RGBA https://github.com/pyglet/pyglet/issues/805

2023-04-17 03:12 UTC, gran4 commented on arcade/gui/widgets/text.py
> +
It looks like this section is creating a problem.

2023-04-19 02:18 UTC, gran4 requested changes

2023-04-19 02:18 UTC, gran4 commented on arcade/gui/widgets/text.py
> +
I think this is the problem

2023-04-19 02:18 UTC, gran4 commented on arcade/gui/widgets/text.py
> +
There shouldn't be 2 spaces

2023-04-25 19:13 UTC, eruvanos commented
@eschan145 For me it looks good in general, just fix the build error and we can merge it

2023-05-02 23:47 UTC, pushfoo commented
Something may be wrong with Sphinx here. The error still occurs locally after removing the top-level docstring from `UITextWidget`.

2023-05-03 00:58 UTC, pushfoo requested changes
1. It's actually the `\n` in `UITextWidget.multiline` causing the error; make it `\\n`
2. Our Sphinx version is broken, but I have a fix for that too (see #1745)
 
I have further suggestions, but the above should get this building & mergable. Having trouble fixing this isn't OP's fault.

2023-05-03 00:58 UTC, pushfoo commented on arcade/gui/widgets/text.py
> +        """
```suggestion
        """
        Get or set the multiline mode.

        Newline characters (``"\\n"``) will only be honored when this is set to ``True``.
        If you want a scrollable text widget, please use :py:class:`~arcade.gui.UITextArea`
        instead.
        """
```
1. The unescaped `\n` is the root of the error sphinx is giving you, but it's not reporting it in the right place due to a bug in our current version
2. `TextArea` does not exist, but `UITextArea` does.
3. The summary line should be separate from the rest of the docstring as shown above.

2023-05-18 11:32 UTC, eruvanos commented on doc/programming_guide/gui/concept.rst
> +|``UIKeyReleaseEvent``      |None                                     |
Should we mention, that UIKeyReleaseEvent inherits from UIKeyEvent and also has `symbol` and `modifiers`?

2023-06-09 01:07 UTC, einarf commented
Fixed the lingering issue with RGB just to check if things build. I'm guessing it should be `RGBOrA`, but I wasn't completely sure. @eruvanos knows?

2023-06-09 12:32 UTC, merged

2023-06-09 12:33 UTC, eruvanos commented
Finally merged, thanks for your work