Correct coordinate calculation for rectangle
pythonarcade/arcade pull request #1741
Opened 2023-04-30 16:45 UTC by vanicat

The new computation
- scale the rectangle as anyother coordinate
- use self.tiled_map.map_size.height * self.tiled_map.tile_size[1] to offset the y coordinate, otherwise they are negative.

Fix  #1740

2023-04-30 19:03 UTC, pvcraven commented
Looks like it didn't pass tests? Please research if you could.

2023-04-30 20:53 UTC, gran4 requested changes
Re-Add the 2 lines:
`x = cur_object.coordinates.x + offset[0]

y = cur_object.coordinates.y + offset[1]`
You deleted. Without them, x and y don't exist.

2023-05-01 07:17 UTC, vanicat commented
I will look at the test after the end of Ludumdare,

2023-05-02 04:54 UTC, vanicat commented
I've updated the patch, and it now pass all the test.
The two line proposed by gran4 was not correct, because the offset must be apply after the scaling (at least, it is what happen for others coordinate computation).

Thanks.

2023-05-03 01:39 UTC, gran4 commented
> I've updated the patch, and it now pass all the test. The two line proposed by gran4 was not correct, because the offset must be apply after the scaling (at least, it is what happen for others coordinate computation).

I didn't mean to fix the bug, I meant to get it to run.

2023-05-03 01:39 UTC, gran4 approved these changes

2023-05-31 02:25 UTC, merged