Improvements to make.py and pyright configuration
pythonarcade/arcade pull request #1746
Opened 2023-05-03 00:46 UTC by cspotcode

I would have submitted as 2x PRs, but unfortunately one depends on the other and stacked PRs don't really work if you're submitting from a fork.

2023-05-03 02:43 UTC, pushfoo requested changes
tl;dr this looks good overall, especially splitting the sections further, but it raises some new questions

In addition to the specific comments I made on the files, I have some questions before we merge. Please keep in mind:

* Not all of them need to be addressed in this PR
* Since I made the suggestions, I can pick up the slack on implementing some of them if you're busy

Questions:

1. Can we group the shell completion commands into a new `"Shell Completion"` group?
2. Can we rearrange the order of the command groups?
3. Can we hide or further control the extra format grouping?
4. Can we move `linkcheck` into `Coding` / `Code Quality`?

It think it's worth cleaning up the output further to be focused on what people use most frequently.  Some of the extra formats are definitely worth keeping (epub, PDF, single html, man, .txt), but not immediately relevant to most users.

2023-05-03 02:43 UTC, pushfoo commented on CONTRIBUTING.md
> +On Mac & Linux, you can run the make script as `./make.py` instead of `python make.py`.
I think it's worth including a warning about `--install-completion` applying to all `make.py` instances rather than just the local one.

2023-05-03 02:43 UTC, pushfoo commented on make.py
>  def qthelp():
For the less standard help commands such as this one, is there group these under `Additional Help Formats` or something similar?

2023-05-03 02:43 UTC, pushfoo commented on make.py
> +@app.command(rich_help_panel="Coding")
`"Code Quality"` would be clearer for this category.

2023-05-03 02:43 UTC, pushfoo commented on make.py
>  def test():
```suggestion
def test():
    """Run unit tests (Run this before making a pull request)!"""
````

2023-05-03 02:43 UTC, pushfoo commented on make.py
> +    Run all linting tasks: ruff and mypy
If you can squeeze it in, I would add a nudge for users to run this before making a PR.

2023-05-03 23:11 UTC, cspotcode commented
Review feedback addressed.

> It think it's worth cleaning up the output further to be focused on what people use most frequently.

Funny enough, for long output like this, if we put them at the top then they're likely to scroll off the top of the screen, leaving only the less important ones visible.

I'd like to merge this PR as-is, and follow-ups can re-order the output.

2023-05-04 02:27 UTC, pushfoo approved these changes
I think this is good, and I agree with the point about the current arrangement of the long output.

Shortening and rearranging the output requires further thought, so we can probably merge this as-is for now.

2023-05-06 21:53 UTC, merged