#1779 Include VideoPlayerView in exports
pythonarcade/arcade pull request #1780
Opened 2023-05-16 22:54 UTC by MrWardKKHS

Will add the video player view for users. Especially helpful in quick prototyping and reducing boilerplate.

2023-05-17 21:04 UTC, pushfoo approved these changes
I think this looks good as-is. :+1:

I didn't even know we had this feature, and I appreciate you bringing it to my attention!

If you have time for a follow-up PR, I'd appreciate it if you could take a look at the following:

1. Add a small public domain MP4 we can include instead of the hard link to a local file on the original author's device
2. Type annotations
3. Better docstrings & formatting

2023-05-17 23:58 UTC, gran4 requested changes

2023-05-17 23:58 UTC, gran4 commented on arcade/experimental/__init__.py
> +from .video_player import VideoPlayerView
```suggestion
from .video_player import VideoPlayerm, VideoPlayerView
```

2023-05-18 00:16 UTC, merged

2023-05-18 00:21 UTC, gran4 commented
@pvcraven it has a mistake.
`from .video_player import VideoPlayer`
`from .video_player import VideoPlayerView`

should be made
`from .video_player import VideoPlayer, VideoPlayerView`