Fallback points for bounding boxes
pythonarcade/arcade pull request #1814
Opened 2023-06-08 20:59 UTC by einarf

2023-06-13 06:25 UTC, gran4 requested changes

2023-06-13 06:25 UTC, gran4 commented on arcade/hitbox/base.py
> +        Crate points for a simple bounding box around an image.
Create is misspelled

2023-06-13 06:25 UTC, gran4 commented on tests/unit/htibox/test_black_image.py
> +    assert tex.hit_box_points == EXPECTED
Wouldn't you want to add a check for when there is no texture?

2023-06-13 06:26 UTC, gran4 commented
I just realized this is a draft... Sorry

2024-02-10 23:58 UTC, einarf commented
> I just realized this is a draft... Sorry

All good! Reviewing things never hurst and I might have missed the typo.

2024-02-11 00:09 UTC, merged