Better tetris demo
pythonarcade/arcade pull request #1932
Opened 2023-11-22 02:16 UTC by asokolsky

Support:

* variable update rate
* more keys, e.g. to slow down/speed up fall rate, rotate in all directions, drop stone

2023-11-28 16:14 UTC, pvcraven commented
Keep in mind with the demos, the idea is to make them as simple as possible. Highlight the new technique only. Let the reader use it as a springboard to make it fancy.

This does some things to improve docs and make simpler. It also expands the game a bit more. Are the expansions needed to show a new concept? If so, make sure the concept is clear. If not, keep it on the simple side.

2023-11-28 17:03 UTC, asokolsky commented
@pvcraven understood and agreed.  I believe the PR does all that.  Plus allowed me to scratch my own itch, and for that opportunity I am grateful.  If you have specific points - I will be happy to address these.

Cheers!

2024-02-18 18:51 UTC, pvcraven requested changes
Really like to keep this example as simple as possible. Specific thoughts in line comments.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +import time
For examples that demonstrate a certain concept, like how-to-do-Tetris I'd like to keep things narrow. Basic concept, as easy as possible to understand.

This should demo how to do a basic Tetris. If we want to center the window on the screen, adjust timings, etc. that should be a separate demo. (As these imports are related to.)

A full bells-and-whistles Tetris should be done as a different example. Probably in a different repository.

A step-by-step tutorial would be another, even more useful, option.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +    [[7, 7],            # Smashboy
These updates are an improvement.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +    return [list(l[::-1]) for l in zip(*shape)]
This would be an ok addition.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +texture_list = [create_texture(color) for color in colors]
This is nicer code. I do sit on the fence for tutorials using list comprehensions as I think they detract from readability. Although this is easier to read than the comprehensions for rotation.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +        self._mh = MARGIN + HEIGHT
For tutorials, should we spell these out?

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +class Board:
This lengthens the code, significantly in what's supposed to be a simple how-to. Seem better for a longer example?

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +        self._desired_update_delay = 1/self._desired_update_rate_per_sec
Variable timing should probably be its own example.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +        return
Center the window should be its own example.

2024-02-18 18:51 UTC, pvcraven commented on arcade/examples/tetris.py
> +        return
This adds a lot of options. I'd suggest pushing to a larger stand-alone or a step-by-step tutorial.

2024-02-20 16:24 UTC, closed without merging