add .tracking and px -> em conversion
pythonarcade/arcade pull request #2365
Opened 2024-09-14 17:53 UTC by DigiDuncan

Added `.tracking` getter/setter to `Text`, as well as `.em_to_px()` and `.px_to_em()` for easy relative-to-font-size value conversion.

An example of why you may want this? To replicate setting this value in Photoshop:
![image](https://github.com/user-attachments/assets/040d408f-d018-4c4a-8584-368bb1f69f3c)
one could write the code:
```py
# Note the Photoshop deals in micro-em, not em.
text.tracking = text.em_to_px(-.120)
```

As you can see, this is needed for some fonts to look good:
![tracking_kerning_demo](https://github.com/user-attachments/assets/6f3545ef-a650-4a6a-9683-47c3d8713bb1)

2024-09-14 19:40 UTC, einarf requested changes

2024-09-14 19:40 UTC, einarf commented on arcade/text.py
> +        """
The setter docstring is never visible in docs. It needs to be merged with property. "Get or set" is a decent indication it's not a read-only property.

2024-09-14 19:40 UTC, einarf commented on arcade/text.py
> +        1em is defined as ``font_size``pt.
You need a space after \`\` to make it valid rst.

2024-09-14 19:40 UTC, einarf commented on arcade/text.py
> +        1em is defined as ``font_size``pt.
You need a space after \`\` to make it valid rst.

2024-09-14 19:40 UTC, einarf commented on arcade/text.py
> +        Returns a pixel amount, or None if the tracking is inconsistent.
You can use google style docstring for the return here to make it more readable in docs

```
Returns:
    Explain the return value
```

2024-09-15 05:31 UTC, DragonMoffon approved these changes

2024-09-15 08:22 UTC, einarf approved these changes

2024-09-15 08:23 UTC, merged