Sprite scale: Preserve performance
pythonarcade/arcade pull request #2389
Opened 2024-10-06 02:20 UTC by einarf

The `Sprite.scale` changes made the property 4-5 times slower. Instead we introduce methods to handle uniform scaling.

2024-10-08 23:10 UTC, DragonMoffon commented
Id like to try one last thing before we go ahead. Since the biggest cost with the Vec2 is around creation and GC I wonder if making a slotted murable Vec-like with support for piecewise operations would be performant enough. Like working with lists it may have a few hickups, but Ill implement `__copy__`

2024-10-08 23:21 UTC, DigiDuncan commented
> Id like to try one last thing before we go ahead. [...]

I'm curious to see this before we push this one through -- the DX is a tad clunky and it won't be forward-compatible with 3.1. I'm fine with it if Dragon's proposal doesn't get done/isn't up to snuff, though, I agree it's a better option then lying to the user as to what the underlying scale is.

2024-10-08 23:48 UTC, einarf commented
The amount of things that broke due to this change was minuscule so I'm not too worried. The new methods are also a lot faster than the scale property can be. Especially when adding and multiplying scale.

This also needs to be checked before merge. Ensure all subclasses of `BasicSprite` is typed to allow a tuple as well.
https://github.com/pythonarcade/arcade/issues/2399

2024-10-10 20:12 UTC, DragonMoffon requested changes

2024-10-10 20:12 UTC, DragonMoffon commented on arcade/examples/sprite_explosion_particles.py
Still has wrong method will fix soon

2024-10-11 10:36 UTC, DragonMoffon approved these changes

2024-10-11 10:37 UTC, DigiDuncan approved these changes
As much as the functions feel a tad clunky still, the speed can't be denied, and I'm more concerned about the return of `scale = float` for DX reasons. Seems good to me until 3.1+.

2024-10-14 12:01 UTC, merged