Fix math point types
pythonarcade/arcade pull request #2430
Opened 2024-10-21 09:24 UTC by Rapen765

Changed functions' return type from `tuple[float, float]` to `Point2`.
Fixed documentation of `rand_vec_magnitude` and `rand_on_circle`.

2024-10-21 23:16 UTC, pushfoo requested changes
**TL;DR:** I'm undecided on the `Point2` change, but I have suggestions on the doc and the doc

@DragonMoffon any thoughts on consistency for `Point2` vs the perf dangers of `Vec2`?

@Rapen765 The CI's linter complaints. Could you please try the following in your local repo clone?
1. Make sure your venv's activated
2. `./make.py format && ./make.py ruff`
3. Commit & push

2024-10-21 23:16 UTC, pushfoo commented on arcade/math.py
> +    Returns a random vector, with random magnitude.
```suggestion
    Return a vector of randomized magnitude pointing in the given direction.
```

2024-10-21 23:16 UTC, pushfoo commented on arcade/math.py
> +        angle (float): The vector angle
```suggestion
        angle (float): The vector angle in radians
```

2024-10-22 02:02 UTC, DragonMoffon commented
I def think Point2 should be used over tuple[float, float] everywhere. The only place it shouldn't be used is anything that returns a `tuple[int, int]` that should have a different alias (`Size2` maybe)

2025-01-01 23:13 UTC, pushfoo approved these changes

2025-01-01 23:15 UTC, merged

2025-01-01 23:16 UTC, pushfoo commented
Merging to nudge velocity back up for 3.0.

2025-01-01 23:16 UTC, pushfoo commented
Ty for the contribution and sorry for the wait!