Center shields.io elements in the README.md file and grammar fixes for multiple documents.
pythonarcade/arcade pull request #2471
Opened 2024-12-08 15:58 UTC by Dwang-ML

Shields.io elements are now centerized in README.md. 

Also made changes in multiple documents, changes include:
 - Grammar fixes
 - Spelling fixes
 - Rephrasing for clear message delivery and more clarity
 - Remove extra characters, such as blank spaces

Documents with changes mentioned above:
 - README.md 
 - CHANGELOG.md
 - CODE_OF_CONDUCT.md
 - CONTRIBUTING.md
 - ISSUE_TEMPLATE.md
 - RELEASE_CHECKLIST.md
 - doc/about/faq.rst
 - doc/about/intro.rst
 
Note: I may be missing some documents in the list above. I apologize if I am.

2024-12-09 18:10 UTC, pvcraven requested changes
Just needs a couple updates then I'm happy merging it in.

2024-12-09 18:10 UTC, pvcraven commented on CODE_OF_CONDUCT.md
> +* Other conducts that could reasonably be considered inappropriate in a
The original singular 'conduct' is correct. Grammarly agrees.

2024-12-09 18:10 UTC, pvcraven commented on doc/about/intro.rst
> +You don’t need to be an expert programmer or game developer to contribute.
No curly quotes in readme markdown for this project please. They do get auto-corrected.

2024-12-10 15:47 UTC, Dwang-ML commented
Will do, I'll finish today.

2024-12-10 17:35 UTC, Dwang-ML commented on doc/about/intro.rst
> +You don’t need to be an expert programmer or game developer to contribute.
> No curly quotes in readme markdown for this project please. They do get auto-corrected.

I'm confused on what you mean by this 😊

2024-12-10 22:04 UTC, Dwang-ML commented on doc/about/intro.rst
> +You don’t need to be an expert programmer or game developer to contribute.
Never mind, I was not observant enough, I apologize.

2024-12-13 21:21 UTC, pvcraven approved these changes

2024-12-13 21:21 UTC, merged

2024-12-13 21:21 UTC, pvcraven commented
Thanks!